# Site settings
title: Tibfib.com

description: > # this means to ignore newlines until "baseurl:"
  The is the website of Will Honey (Tibfib) who is a web developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tibfib.com" # the base hostname & protocol for your site
production_url: "https://tibfib.com"
asset_path: /assets/
permalink: pretty

tagline:
author :
  name : Will Honey
  email : will@tibfib.com
  github : Tibfib
  twitter : Tibfib

paginate: 5
# Build settings
markdown: kramdown
plugins: [jekyll-paginate]
